"""Tests for intake, triage and the report.

Generated by Claude Code.

Claude is never called here. `_ask_claude` is patched in every test that
exercises the triage, so the suite is deterministic, free to run, and works
with no API key present. The triage itself is called directly rather than
through the queue, since what's under test is the decision it makes, not
Frappe's ability to run a job.
"""

from unittest.mock import patch

import frappe
from frappe.tests import IntegrationTestCase

from lead_intake import api, triage


def enquiry(**overrides):
	payload = {
		"external_enquiry_id": frappe.generate_hash(length=10),
		"contact_name": "Test Person",
		"email": f"{frappe.generate_hash(length=10)}@example.test",
		"message": "Our phone system keeps dropping calls and we want to move to VoIP.",
	}
	payload.update(overrides)
	return payload


class TestIntake(IntegrationTestCase):
	def test_creates_a_lead(self):
		payload = enquiry(company_name="Beck Orthodontics")
		result = api.intake_enquiry(**payload)

		self.assertFalse(result["duplicate"])
		lead = frappe.get_doc("Lead", result["lead"])
		self.assertEqual(lead.company_name, "Beck Orthodontics")
		self.assertEqual(lead.custom_external_enquiry_id, payload["external_enquiry_id"])
		self.assertEqual(lead.custom_enquiry_message, payload["message"])

	def test_repeat_enquiry_id_returns_the_same_lead(self):
		payload = enquiry()
		first = api.intake_enquiry(**payload)

		before = frappe.db.count("Lead")
		second = api.intake_enquiry(**payload)
		after = frappe.db.count("Lead")

		self.assertTrue(second["duplicate"])
		self.assertEqual(second["lead"], first["lead"])
		self.assertEqual(before, after, "a duplicate must not create a Lead")

	def test_missing_fields_are_rejected(self):
		result = api.intake_enquiry(external_enquiry_id="X-1")

		self.assertIn("error", result)
		for field in ("contact_name", "email", "message"):
			self.assertIn(field, result["error"])

	def test_invalid_email_is_rejected(self):
		result = api.intake_enquiry(**enquiry(email="not-an-email"))

		self.assertIn("error", result)
		self.assertNotIn("lead", result)


class TestTriage(IntegrationTestCase):
	def _lead_for(self, message):
		result = api.intake_enquiry(**enquiry(message=message))
		return result["lead"]

	def test_out_of_range_response_falls_back_to_rules(self):
		lead = self._lead_for("Our file server is showing a ransomware warning.")

		bogus = {
			"service_interest": "Nonsense",  # not one of the allowed values
			"qualification_status": "Extremely Qualified",
			"summary": "whatever the model felt like",
		}
		with patch.object(triage, "_ask_claude", return_value=bogus):
			with patch.object(triage, "_api_key", return_value="sk-ant-test"):
				triage.triage_lead(lead)

		doc = frappe.get_doc("Lead", lead)
		self.assertEqual(doc.custom_triage_source, "Rules")
		self.assertIn(doc.custom_service_interest, ("IT",))
		self.assertNotEqual(doc.custom_service_interest, "Nonsense")

	def test_a_valid_response_is_used(self):
		lead = self._lead_for("We need someone to run our Microsoft 365 tenant.")

		verdict = {
			"service_interest": "IT",
			"qualification_status": "Qualified",
			"summary": "Wants managed Microsoft 365 support.",
		}
		with patch.object(triage, "_ask_claude", return_value=verdict):
			with patch.object(triage, "_api_key", return_value="sk-ant-test"):
				triage.triage_lead(lead)

		doc = frappe.get_doc("Lead", lead)
		self.assertEqual(doc.custom_triage_source, "Claude")
		self.assertEqual(doc.custom_service_interest, "IT")
		self.assertEqual(doc.qualification_status, "Qualified")
		self.assertEqual(doc.custom_ai_summary, "Wants managed Microsoft 365 support.")

	def test_a_humans_choice_is_never_overwritten(self):
		lead = self._lead_for("Our phone system keeps dropping calls.")

		# A salesperson gets there first.
		doc = frappe.get_doc("Lead", lead)
		doc.db_set(
			{
				"custom_service_interest": "Strategy",
				"custom_triage_source": "Manual",
				"qualification_status": "Qualified",
			}
		)

		verdict = {
			"service_interest": "VoIP",
			"qualification_status": "Unqualified",
			"summary": "Phone system trouble.",
		}
		with patch.object(triage, "_ask_claude", return_value=verdict):
			with patch.object(triage, "_api_key", return_value="sk-ant-test"):
				triage.triage_lead(lead)

		doc.reload()
		self.assertEqual(doc.custom_service_interest, "Strategy")
		self.assertEqual(doc.custom_triage_source, "Manual")
		self.assertEqual(doc.qualification_status, "Qualified")

	def test_no_api_key_still_classifies(self):
		lead = self._lead_for("We were hit by ransomware this morning and nobody can work.")

		with patch.object(triage, "_api_key", return_value=None):
			triage.triage_lead(lead)

		doc = frappe.get_doc("Lead", lead)
		self.assertEqual(doc.custom_triage_source, "Rules")
		self.assertEqual(doc.custom_service_interest, "IT")
		self.assertEqual(doc.qualification_status, "Qualified")


class TestReport(IntegrationTestCase):
	def test_counts_by_service(self):
		from lead_intake.lead_intake.report.lead_pipeline_summary.lead_pipeline_summary import (
			execute,
		)

		marker = frappe.generate_hash(length=8)
		for _ in range(2):
			lead = api.intake_enquiry(**enquiry(message=f"VoIP phones please {marker}"))["lead"]
			with patch.object(triage, "_api_key", return_value=None):
				triage.triage_lead(lead)

		_columns, data = execute({"from_date": frappe.utils.nowdate(), "to_date": frappe.utils.nowdate()})
		by_service = {row["service"]: row for row in data}

		self.assertIn("VoIP", by_service)
		self.assertGreaterEqual(by_service["VoIP"]["total"], 2)
		self.assertEqual(
			by_service["VoIP"]["total"],
			by_service["VoIP"]["qualified"]
			+ by_service["VoIP"]["in_process"]
			+ by_service["VoIP"]["unqualified"],
			"every lead must land in exactly one qualification bucket",
		)
